---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret-name
  namespace: default
type: Opaque
data:
  personal_access_token: YXl5eXkgbG1hbw==
---
apiVersion: com.dstancu.databricks/v1
kind: GitCredential
metadata:
  name: example-credential
  namespace: default
spec:
  secret_name: my-secret-name
  credential:
    git_username: mach-kernel
    git_provider: gitHub